name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install libicu-dev
      run: sudo apt-get update;sudo apt-get install libicu-dev -y

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Build and Test
      shell: pwsh
      run: |
        .\Build.ps1 -version "1.0.0"
