name: .NET Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install libicu-dev
      run: sudo apt-get update;sudo apt-get install libicu-dev -y

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Test with dotnet
      run: dotnet test --configuration Release --no-build --verbosity normal

    - name: Pack with dotnet
      run: |
        dotnet pack ./QQWry --configuration Release --no-build --verbosity normal
        dotnet pack ./QQWry.DependencyInjection --configuration Release --no-build --verbosity normal
